<?php

namespace Database\Seeders;

use App\Models\ArchaeologicalPlace;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BitolaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        collect([
            ['name' => 'Тепиџик', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Тепиџик%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Арбасиновец', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Арбасиновец%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Отажна Маала', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Отажна Маала%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Селиште', 'description' => 'хеленистичко, римско време и среден век', 'link' => 'https://www.openstreetmap.org/search?query=Селиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Слатина', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Слатина%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Самовили', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Самовили%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Висои', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Висои%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Воден Дол', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Воден Дол%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Грабечка Река', 'description' => 'хеленистичко и римско време', 'link' => 'https://www.openstreetmap.org/search?query=Грабечка Река%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Градиште', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Женски Дол', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Женски Дол%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Плочи', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Плочи%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Ристов Кладенец', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Ристов Кладенец%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Црквиште', 'description' => 'раноантичко и хеленистичко време', 'link' => 'https://www.openstreetmap.org/search?query=Црквиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Шукаловец', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Шукаловец%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Арбасиновец', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Арбасиновец%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Градиште', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Во Селото', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Во Селото%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Стара Црква', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Стара Црква%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Ѓорѓија', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Ѓорѓија%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Бадем Балери', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Бадем Балери%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Гургур Тумба', 'description' => 'неолит', 'link' => 'https://www.openstreetmap.org/search?query=Гургур Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Еврејски Гробишта', 'description' => 'неолит', 'link' => 'https://www.openstreetmap.org/search?query=Еврејски Гробишта%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кале', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Троица', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Троица%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Хераклеја Линкестидска', 'description' => 'хеленистичко, римско, доцноантичко време и среден век', 'link' => 'https://www.openstreetmap.org/search?query=Хераклеја Линкестидска%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Магарешко Мовче', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Магарешко Мовче%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Спас', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Спас%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Стари Лозја', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Стари Лозја%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Бела Црква', 'description' => 'неолит', 'link' => 'https://www.openstreetmap.org/search?query=Бела Црква%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Браилово', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Браилово%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Грдилово', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Грдилово%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Сарај', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Сарај%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Брод', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Брод%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Џепен', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Џепен%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Илкова Чешма', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Илкова Чешма%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Петка', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Петка%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Димитрија', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Димитрија%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Арапски Гробишта', 'description' => 'римско време и среден век', 'link' => 'https://www.openstreetmap.org/search?query=Арапски Гробишта%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Бурнуица', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Бурнуица%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Горно Маало', 'description' => 'римско време и среден век', 'link' => 'https://www.openstreetmap.org/search?query=Горно Маало%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Слатин Вир', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Слатин Вир%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Буковски Манастир', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Буковски Манастир%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кутлиште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Кутлиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Неолјани', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Неолјани%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Црквиште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Црквиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Букришки Вис', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Букришки Вис%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Висок Рид', 'description' => 'бакарно и бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Висок Рид%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Прогон', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Прогон%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Велушка Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Велушка Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Садеви', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Садеви%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Поројница', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Поројница%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Арапски Гробишта', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Арапски Гробишта%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Бајрак', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Бајрак%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Манастириште', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Манастириште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Маркова Нога', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Маркова Нога%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Црквиште', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Црквиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Градиште', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Грамадиште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Грамадиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Ограѓе', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Ограѓе%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Вакафско Место', 'description' => 'хеленистичко време', 'link' => 'https://www.openstreetmap.org/search?query=Вакафско Место%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кале', 'description' => 'хеленистичко, римско и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Маркоица', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Маркоица%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Батаци', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Батаци%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Калајџица', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Калајџица%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Арматуш', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Арматуш%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Градиште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Лудеј', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Лудеј%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Ритче', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Ритче%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Широка Падина', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Широка Падина%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Шупуро', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Шупуро%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Братиндолска Река', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Братиндолска Река%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Варвара', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Варвара%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Ограѓе', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Ограѓе%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Недела', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Недела%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Старо Село', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Старо Село%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Арапски Гробишта', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Арапски Гробишта%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Голема Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Голема Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Горна Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Горна Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Ерековски Ливади', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Ерековски Ливади%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Плочи', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Плочи%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Селиште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Селиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кале', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Старо Село', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Старо Село%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Суви Ливади', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Суви Ливади%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Долна Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Долна Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Смаилица', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Смаилица%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба Гробишта', 'description' => 'бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба Гробишта%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Богородица', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Богородица%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Петка', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Петка%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кале', 'description' => 'доцноантичко време и среден век', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Прогон', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Прогон%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Ќерамидница', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Ќерамидница%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Герамидница', 'description' => 'бронзено и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Герамидница%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Петка', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Петка%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Север I', 'description' => 'неолит и бакарно време', 'link' => 'https://www.openstreetmap.org/search?query=Север I%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Север II', 'description' => 'неолит и бакарно време', 'link' => 'https://www.openstreetmap.org/search?query=Север II%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Домус Поле I', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Домус Поле I%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Сакојци', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Сакојци%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Бели Камења', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Бели Камења%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Селиште', 'description' => 'хеленистичко време', 'link' => 'https://www.openstreetmap.org/search?query=Селиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Арангел', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Арангел%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Тодот', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Тодот%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Во Селото', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Во Селото%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Димитрија', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Димитрија%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Чарлиски Тумби', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Чарлиски Тумби%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Градски Пат', 'description' => 'хеленистилко и римско време', 'link' => 'https://www.openstreetmap.org/search?query=Градски Пат%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Коловозник', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Коловозник%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Вакафски Ледиње', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Вакафски Ледиње%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Во Селото', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Во Селото%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Губерница', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Губерница%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Дабички', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Дабички%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Дабје', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Дабје%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кочишта', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Кочишта%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Поројница', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Поројница%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Ластојца', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Ластојца%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кале', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Чагорско Кале', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Чагорско Кале%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кале', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Богородица', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Богородица%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Старо Село', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Старо Село%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Старо Село', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Старо Село%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Старо Жабени', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Старо Жабени%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Бел Камен', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Бел Камен%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Влаку', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Влаку%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Градиште', 'description' => 'раноантичко, доцноантичко време и среден век', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Дабица', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Дабица%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кералот', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Кералот%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Саат Тумба', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Саат Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Илија', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Илија%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Сртот', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Сртот%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Марта', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Марта%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба Чебрен', 'description' => 'римско и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба Чебрен%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Ѓорѓи', 'description' => 'римско и доцноантичко време и среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Ѓорѓи%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Студена Чешма', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Студена Чешма%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Мечкарец', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Мечкарец%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кули', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Кули%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'неолитско, бакарно и бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Ќосеица', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Ќосеица%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Жеждево', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Жеждево%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Старо Село', 'description' => 'неолитско, бакарно и бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Старо Село%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Црна Земја', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Црна Земја%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Чукут', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Чукут%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба II', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба II%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Мулојца', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Мулојца%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Рамно', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Рамно%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Јуџек', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Јуџек%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Градини', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Градини%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кумбуралар', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Кумбуралар%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Врчва', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Врчва%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Крклино', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Крклино%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Крклински Ливади', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Крклински Ливади%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Падарница', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Падарница%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Грамаѓе', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Грамаѓе%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Мирои Орници', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Мирои Орници%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кула', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Кула%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Магловска Нива', 'description' => 'неолитско и римско време', 'link' => 'https://www.openstreetmap.org/search?query=Магловска Нива%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'неолитско и римско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба во Селото', 'description' => 'неолитско време и среден век', 'link' => 'https://www.openstreetmap.org/search?query=Тумба во Селото%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кале', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Калуѓери', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Калуѓери%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кора', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кора%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Црнобучки Рид', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Црнобучки Рид%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Крс', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Крс%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Бресје', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Бресје%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Дабички Пат', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Дабички Пат%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Голема Тумба', 'description' => 'бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Голема Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Мала Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Мала Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Ќерамидница[а]', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Ќерамидница[а]%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Мучеинци[а]', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Мучеинци[а]%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Во Селото', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Во Селото%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Долни Леоник', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Долни Леоник%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Калуѓери', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Калуѓери%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Коритница', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Коритница%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Ограда', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Ограда%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Римски Гробишта', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Римски Гробишта%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Старомаковски Дол', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Старомаковски Дол%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Маркова Кула', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Маркова Кула%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Попова Нива', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Попова Нива%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Старо Село', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Старо Село%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Никола', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Никола%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Светица', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Светица%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Рековчанска Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Рековчанска Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Роњевска Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Роњевска Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Селска Црква', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Селска Црква%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба во Ливаѓето', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба во Ливаѓето%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба Трнска', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба Трнска%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Сред Село', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Сред Село%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Школска Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Школска Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Шемоска Тумба', 'description' => 'неолитско и бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Шемоска Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Бел Камен', 'description' => 'железно и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Бел Камен%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Еленик', 'description' => 'хеленистичко и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Еленик%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Лилјак', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Лилјак%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Рупа', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Рупа%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Шипур', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Шипур%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Ограѓе', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Ограѓе%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Салија Чешма', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Салија Чешма%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Горно Село', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Горно Село%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кај Црквата', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Кај Црквата%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Долни Висои', 'description' => 'неолитско и бакарно време', 'link' => 'https://www.openstreetmap.org/search?query=Долни Висои%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Бела Црква', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Бела Црква%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'неолитско и римско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Гајтаница', 'description' => 'неолитско и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Гајтаница%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Горни Ливади', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Горни Ливади%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Никола', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Никола%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Старо Село', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Старо Село%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Ана', 'description' => 'хеленистичко време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Ана%2C%20Македонија', 'city_id' => 3],
            ['name' => 'На Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=На Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Трн Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Трн Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Атанас', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Св. Атанас%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Никола', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Св. Никола%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Југ I', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Југ I%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Југ II', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Југ II%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Југ III', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Југ III%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Исток I', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Исток I%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Исток II', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Исток II%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кале', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Маркова Стапалка', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Маркова Стапалка%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Најденка', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Најденка%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Мавер', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Мавер%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Богородица', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Богородица%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба в Село', 'description' => 'бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба в Село%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Бачилиште', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Бачилиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Исток 1', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Исток 1%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Исток 2', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Исток 2%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Полигон', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Полигон%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Бара Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Бара Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Дупки', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Дупки%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Школо', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Школо%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Црквиште', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Црквиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'неолитско, бакарно и бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Копилица', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Копилица%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Вишна', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Вишна%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Раменска Грмада', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Раменска Грмада%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Раменска Тумба', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Раменска Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Чуки', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Чуки%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Бел Камен', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Бел Камен%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Каранка', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Каранка%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Лисичин Камен', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Лисичин Камен%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Сламите', 'description' => 'железно и доцноримско време', 'link' => 'https://www.openstreetmap.org/search?query=Сламите%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Змеиште', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Змеиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Стари Гробови', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Стари Гробови%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Во Селото', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Во Селото%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Смаилица', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Смаилица%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумби', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумби%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Арнаутски Пат', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Арнаутски Пат%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Манастирска Црква', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Манастирска Црква%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Стара Црква', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Стара Црква%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Старо Село', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Старо Село%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Василичини Гробишта', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Василичини Гробишта%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кале', 'description' => 'хеленистичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Крчин', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Крчин%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кутлина', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Кутлина%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кучкина Леска', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Кучкина Леска%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Црквиште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Црквиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Чешмина', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Чешмина%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Манастир', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Манастир%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Над Чаир', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Над Чаир%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Градиште', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Петалинско Кале', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Петалинско Кале%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Марково Кале', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Марково Кале%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Галиќ', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Галиќ%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Црквиште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Црквиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Пешта', 'description' => 'римско и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Пешта%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кале', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Долна Црква', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Долна Црква%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Пусти Манастир', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Пусти Манастир%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Бројанец', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Бројанец%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Бртви', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Бртви%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Дибек', 'description' => 'хеленистичко време', 'link' => 'https://www.openstreetmap.org/search?query=Дибек%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Ѓорев Рид', 'description' => 'неолитско и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Ѓорев Рид%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Ѓорчева Воденица', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Ѓорчева Воденица%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Манастирец', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Манастирец%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Туриграв', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Туриграв%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Ума', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Ума%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Шуплевец', 'description' => 'бакарно време', 'link' => 'https://www.openstreetmap.org/search?query=Шуплевец%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Трап', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Трап%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Црквиште', 'description' => 'неолитско и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Црквиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Петка', 'description' => 'старохристијанко време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Петка%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Голема Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Голема Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Мала Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Мала Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Црквиште', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Црквиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кале', 'description' => 'железно и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Трновски Лозја', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Трновски Лозја%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Герамидница', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Герамидница%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Дапче', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Дапче%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Селиште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Селиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Трновско Кале', 'description' => 'хеленистичко време', 'link' => 'https://www.openstreetmap.org/search?query=Трновско Кале%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Кале', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Патрица', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Патрица%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Шума', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Шума%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Речиште', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Речиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Клепач', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Клепач%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Крсто', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Крсто%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Рупка', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Рупка%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Петка', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Петка%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тврди Град', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Тврди Град%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Варварица', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Варварица%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Градиште', 'description' => 'хеленистичко и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Гулев Рид', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Гулев Рид%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Под Селото', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Под Селото%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Самовилец', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Самовилец%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Тумба', 'description' => 'неолитско и бакарно време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Св. Димитрија', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Димитрија%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Црквиште', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Црквиште%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Црнобуки', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Црнобуки%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Пасјак', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Пасјак%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Старо Село', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Старо Село%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Стара Црква', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Стара Црква%2C%20Македонија', 'city_id' => 3],
            ['name' => 'Манастириште', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Манастириште%2C%20Македонија', 'city_id' => 3],
        ])->each(fn($arPlace) => ArchaeologicalPlace::query()->create($arPlace));
    }
}
