<?php

namespace Database\Seeders;

use App\Models\ArchaeologicalPlace;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OhridSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        collect([
            ['name' => 'Добра Вода', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Добра Вода%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Катуништа (Косарко Нива)', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Катуништа (Косарко Нива)%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Атанасија', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Атанасија%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Василиј', 'description' => 'развиен среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Василиј%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Јован - Кај Смрекана', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Јован - Кај Смрекана%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Задел', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Задел%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Манастирче', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Манастирче%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Богородица', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Богородица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Брежанско Градиште', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Брежанско Градиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Во Селото', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Во Селото%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Градиште - Кула', 'description' => 'железно и хеленистичко време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште - Кула%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Широко Гариште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Широко Гариште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Манастириште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Манастириште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Умалиште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Умалиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Зад Кула', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Зад Кула%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Кале', 'description' => 'доцноантичко време и среден век', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Котелица - Св. Никола', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Котелица - Св. Никола%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Мантица - Бозоица', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Мантица - Бозоица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'На Лазој', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=На Лазој%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Олмец - Кулиште', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Олмец - Кулиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Димитрија', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Димитрија%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Илија', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Илија%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Турски Гробишта', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Турски Гробишта%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Чурила', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Чурила%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Џамијата', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Џамијата%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Богородица Пречиста', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Богородица Пречиста%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Велестово', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Велестово%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Кромидишта', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Кромидишта%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Рача', 'description' => 'доцноантичко време; среден век', 'link' => 'https://www.openstreetmap.org/search?query=Рача%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Селиште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Селиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Стара Рача', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Стара Рача%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Бучишта', 'description' => 'доцноантичко време; старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Бучишта%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Велмешко Градиште', 'description' => 'бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Велмешко Градиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Вишин Дол', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Вишин Дол%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Гладница', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Гладница%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Горица', 'description' => 'развиен среден век', 'link' => 'https://www.openstreetmap.org/search?query=Горица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Горни Јаворец', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Горни Јаворец%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Горнополско Градиште', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Горнополско Градиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Грамаѓе', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Грамаѓе%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Иванова Ливада - Икона', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Иванова Ливада - Икона%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Икона - Блато', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Икона - Блато%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Калуѓерица', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Калуѓерица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Кутлина', 'description' => 'неолитско, бакарно, бронзено и железно време; ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Кутлина%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Манастириште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Манастириште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Оџа Бавча', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Оџа Бавча%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Пашина Горица', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Пашина Горица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Петте Дабје', 'description' => 'римско и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Петте Дабје%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Пештера Јаорец', 'description' => 'палеолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Пештера Јаорец%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Писан Камен', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Писан Камен%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Попов Дол', 'description' => 'доцноантичко време и ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Попов Дол%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Селиште Јаорец', 'description' => 'развиен и доцен среден век', 'link' => 'https://www.openstreetmap.org/search?query=Селиште Јаорец%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Селце', 'description' => 'развиен среден век', 'link' => 'https://www.openstreetmap.org/search?query=Селце%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Скала', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Скала%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Скала', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Скала%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Средна Горица', 'description' => 'ранословенско време', 'link' => 'https://www.openstreetmap.org/search?query=Средна Горица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Црквиште', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Црквиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Шивлица', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Шивлица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Климент', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Климент%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Никола', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Никола%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Стари Гробишта', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Стари Гробишта%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Нивишта', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Нивишта%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Црквиште - Петрчани', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Црквиште - Петрчани%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Војо', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Војо%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Горица', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Горица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Кула', 'description' => 'хеленистичко време, доцноантичко време и среден век', 'link' => 'https://www.openstreetmap.org/search?query=Кула%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Спас - Црквиште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Спас - Црквиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Трумени Гумења', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Трумени Гумења%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Черенец', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Черенец%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Горенци', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Горенци%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Пуст Манастир', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Пуст Манастир%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Тигари', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Тигари%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Требеништа - Сува Чешма', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Требеништа - Сува Чешма%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Горица', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Горица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Полица', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Полица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Салоко Ливада', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Салоко Ливада%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Ќерија - Долчиња', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Ќерија - Долчиња%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Зластрана', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Зластрана%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Богородица', 'description' => 'развиен среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Богородица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Баник', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Баник%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Василички Гробишта', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Василички Гробишта%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Градиште', 'description' => 'бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Дујгас', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Дујгас%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Лак - Предикамница', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Лак - Предикамница%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Недела', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Недела%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Елшани', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Елшани%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Купејнца', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Купејнца%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Градиште', 'description' => 'брозено време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Богородица Пречиста - Раштани', 'description' => 'старохристијанско време; среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Богородица Пречиста - Раштани%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Никола', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Никола%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Страишта', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Страишта%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Зглавиница - Старо Село', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Зглавиница - Старо Село%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Манастириште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Манастириште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Димитрија', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Димитрија%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Градиште', 'description' => 'хеленистичко време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Мало Коњско', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Мало Коњско%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Горна Горица', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Горна Горица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Градиште', 'description' => 'бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Илија', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Илија%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Јован', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Јован%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Сред Село', 'description' => 'хеленистичко време', 'link' => 'https://www.openstreetmap.org/search?query=Сред Село%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Црквата', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Црквата%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Горно Село - Св. Богородица', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Горно Село - Св. Богородица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Кулишта', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кулишта%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Манастириште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Манастириште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Трно Селиште - Аноите', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Трно Селиште - Аноите%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Ќуле - Градиште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Ќуле - Градиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Градиште', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Манастир', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Манастир%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Мега', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Мега%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Белио', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Белио%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Горица', 'description' => 'неолитско, бронзено и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Горица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Лелешница', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Лелешница%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Никола', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Никола%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Петкина Нива', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Петкина Нива%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Спас - Вознесение', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Спас - Вознесение%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Сред Село', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Сред Село%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Градиште', 'description' => 'бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Думејнчка Горица', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Думејнчка Горица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Атанасиј', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Атанасиј%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Богородица', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Богородица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Петар', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Петар%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Сисвети', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Сисвети%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Старо Село - Црквиште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Старо Село - Црквиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Бучила', 'description' => 'неолитско време; римско време', 'link' => 'https://www.openstreetmap.org/search?query=Бучила%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Градиште - Вилиците', 'description' => 'хеленистичко време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште - Вилиците%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Раица - Манастири', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Раица - Манастири%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Атанасија', 'description' => 'римско време; среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Атанасија%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Богородица', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Богородица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Илија', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Илија%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Наум', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Наум%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Никола - Селски Гробишта', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Никола - Селски Гробишта%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Петка', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Петка%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Стара Колиба - Ќошот', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Стара Колиба - Ќошот%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Турски Гробишта', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Турски Гробишта%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Горно Поле', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Горно Поле%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Горно Црквиште - На Мартинец', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Горно Црквиште - На Мартинец%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Зад Лозја', 'description' => 'доцен среден век', 'link' => 'https://www.openstreetmap.org/search?query=Зад Лозја%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Криви Загони - Лозишта', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Криви Загони - Лозишта%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Редеш', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Редеш%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Илија', 'description' => 'железно време; среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Илија%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Селиште Ивани', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Селиште Ивани%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Црвени Брегови', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Црвени Брегови%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Црква Св. Петар', 'description' => 'доцен среден век', 'link' => 'https://www.openstreetmap.org/search?query=Црква Св. Петар%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Црквиште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Црквиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Чешмите - Магда', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Чешмите - Магда%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Градиште - Кутлиња', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште - Кутлиња%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Мрамор', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Мрамор%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Рупи', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Рупи%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Лаишта', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Лаишта%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Црква', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Црква%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Црква - Бело Гумно', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Црква - Бело Гумно%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Селиште - На Брестон', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Селиште - На Брестон%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Горно Село', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Горно Село%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Лажиште - Вилипец', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Лажиште - Вилипец%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Мадем', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Мадем%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Релејца', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Релејца%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Старечки Дол', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Старечки Дол%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Требишки Рид', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Требишки Рид%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Црвејнца', 'description' => 'неолитско време; хеленистичко време и среден век', 'link' => 'https://www.openstreetmap.org/search?query=Црвејнца%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Маалски Рид', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Маалски Рид%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Мауцкер', 'description' => 'хеленистичко време', 'link' => 'https://www.openstreetmap.org/search?query=Мауцкер%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Орман', 'description' => 'неолитско време; римско време', 'link' => 'https://www.openstreetmap.org/search?query=Орман%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Чекоштина', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Чекоштина%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Оровник', 'description' => 'хеленистичко и римско време', 'link' => 'https://www.openstreetmap.org/search?query=Оровник%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Под Црквата', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Под Црквата%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Тројани', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Тројани%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Античка Фурна', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Античка Фурна%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Антички Театар', 'description' => 'хеленистичко време', 'link' => 'https://www.openstreetmap.org/search?query=Антички Театар%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Видобишта', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Видобишта%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Горица', 'description' => 'римско време; среден век', 'link' => 'https://www.openstreetmap.org/search?query=Горица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Горно Трново', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Горно Трново%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Гумништа - Инвалидско Одморалиште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Гумништа - Инвалидско Одморалиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Дебој', 'description' => 'хеленистичко време, римско време и среден век; старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Дебој%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Долно Трново', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Долно Трново%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Енгелана (Кулишта)', 'description' => 'раноантичко и хеленистичко време', 'link' => 'https://www.openstreetmap.org/search?query=Енгелана (Кулишта)%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Карабегомала', 'description' => 'хеленистичко време', 'link' => 'https://www.openstreetmap.org/search?query=Карабегомала%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Козлук', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Козлук%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Комплекс „Попарница“', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Комплекс „Попарница“%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Комплекс „Св. Климент“', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Комплекс „Св. Климент“%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Комплекс „Св. Пантелејмон“ (Плаошник)', 'description' => 'старохристијанско време и среден век', 'link' => 'https://www.openstreetmap.org/search?query=Комплекс „Св. Пантелејмон“ (Плаошник)%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Комплекс „Св. Софија“', 'description' => 'римско време, доцноантичко време и ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Комплекс „Св. Софија“%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Комплекс „Св. Спас“', 'description' => 'римско време; старохристијанско време и среден век', 'link' => 'https://www.openstreetmap.org/search?query=Комплекс „Св. Спас“%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Комплекс „Стара Чаршија“', 'description' => 'железно време и ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Комплекс „Стара Чаршија“%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Кошишта', 'description' => 'хеленистичко време, римско време и ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Кошишта%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Лабино', 'description' => 'од брозено време до ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Лабино%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Лихнид', 'description' => 'од неолитско до доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Лихнид%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Панзир', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Панзир%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Самуилова Tврдина', 'description' => 'хеленистичко време, доцноантичко време и среден век', 'link' => 'https://www.openstreetmap.org/search?query=Самуилова Tврдина%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Еразмо', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Еразмо%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Стефан - Горица', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Стефан - Горица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Студенчишта', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Студенчишта%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Хермелеја', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Хермелеја%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Кула', 'description' => 'доцноантичко време и среден век', 'link' => 'https://www.openstreetmap.org/search?query=Кула%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Манастириште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Манастириште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Градиште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Залив на Коските', 'description' => 'доцнобронзено и раножелезно време', 'link' => 'https://www.openstreetmap.org/search?query=Залив на Коските%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Старо Село', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Старо Село%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Црквиште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Црквиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Џамиште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Џамиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Недела', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Недела%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Корија - Манастириште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Корија - Манастириште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Селиште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Селиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Чешма', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Чешма%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Кумбаревци', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Кумбаревци%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Макла', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Макла%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Манастири', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Манастири%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Рамненски Лозја', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Рамненски Лозја%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Атанасија', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Атанасија%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Варвара', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Варвара%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Врачи', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Врачи%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Илија', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Илија%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Туше Варница', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Туше Варница%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Чешма', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Чешма%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Задружни Штали', 'description' => 'железно и римско време', 'link' => 'https://www.openstreetmap.org/search?query=Задружни Штали%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Ковче - Падина', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Ковче - Падина%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Лозишта', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Лозишта%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Манастириште - Св. Недела', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Манастириште - Св. Недела%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Полчани', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Полчани%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Дабје', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Дабје%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Долиште', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Долиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Манастириште', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Манастириште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Пирчишта', 'description' => 'неолитско време; среден век', 'link' => 'https://www.openstreetmap.org/search?query=Пирчишта%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Горна Црква', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Горна Црква%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Никола', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Никола%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Кулишта', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Кулишта%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Бањи - Бигори', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Бањи - Бигори%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Градиште', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Избичани', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Избичани%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Калуѓероец', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Калуѓероец%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Преслоп', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Преслоп%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Јован Бигорски', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Јован Бигорски%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Селце', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Селце%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Брце', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Брце%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Горица', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Горица%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Еленишта', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Еленишта%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Јаковски Куќи', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Јаковски Куќи%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Ковачница', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Ковачница%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Држилец', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Држилец%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Алистрати', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Алистрати%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Бароец', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Бароец%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Дере - Кај Чешмата', 'description' => 'брозено време', 'link' => 'https://www.openstreetmap.org/search?query=Дере - Кај Чешмата%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Забрдо', 'description' => 'железно време; хеленистичко и римско време; ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Забрдо%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Св. Мартинија', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Мартинија%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Требеништа', 'description' => 'железно, архаично и хеленистичко време', 'link' => 'https://www.openstreetmap.org/search?query=Требеништа%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Требенишко кале', 'description' => 'бронзено, железно, хеленистичко и римско време', 'link' => 'https://www.openstreetmap.org/search?query=Требенишко кале%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Црква', 'description' => 'ран среден вен', 'link' => 'https://www.openstreetmap.org/search?query=Црква%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Црквиште', 'description' => 'среден вен', 'link' => 'https://www.openstreetmap.org/search?query=Црквиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Глајшо - Селиште', 'description' => 'среден вен', 'link' => 'https://www.openstreetmap.org/search?query=Глајшо - Селиште%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Градиште - Осој', 'description' => 'среден вен', 'link' => 'https://www.openstreetmap.org/search?query=Градиште - Осој%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Заум', 'description' => 'старохристијанско време; среден век', 'link' => 'https://www.openstreetmap.org/search?query=Заум%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Кале', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Црна Пеш - Крстон Заб', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Црна Пеш - Крстон Заб%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Радеица - Странана', 'description' => 'ран среден вен', 'link' => 'https://www.openstreetmap.org/search?query=Радеица - Странана%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Старо Село', 'description' => 'среден вен', 'link' => 'https://www.openstreetmap.org/search?query=Старо Село%2C%20Македонија', 'city_id' => 6],
            ['name' => 'Нивата од Васил Бучкоски', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Нивата од Васил Бучкоски%2C%20Македонија', 'city_id' => 6],
        ])->each(fn($arPlace) => ArchaeologicalPlace::query()->create($arPlace));
    }
}
