<?php

namespace Database\Seeders;

use App\Models\ArchaeologicalPlace;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SkopjeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        collect([
            ['name' => 'Кале', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Муџица', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Муџица%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Кисел Вир', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Кисел Вир%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Криви Дол', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Криви Дол%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Црквиште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Црквиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Бадеријана (Дрма)', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Бадеријана (Дрма)%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Китка', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Китка%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Стар Пат', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Стар Пат%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Бања', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Бања%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Дуло', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Дуло%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Св. Ѓорѓи', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Ѓорѓи%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Барово', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Барово%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Градиште', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Св. Атанасија', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Атанасија%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Зад Воденицата', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Зад Воденицата%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Чешма', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Чешма%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Барда', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Барда%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Лозје', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Лозје%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Св. Ѓорѓи', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Ѓорѓи%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Градиште', 'description' => 'железно, раноантичко, римско и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Ѓорѓоец', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Ѓорѓоец%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Царевец', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Царевец%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Видране', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Видране%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Ирма', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Ирма%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Кале', 'description' => 'раноантичко, доцноантичко време и среден век', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Латина', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Латина%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Карабаир', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Карабаир%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Кула', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кула%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Јазбине', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Јазбине%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Градиште', 'description' => 'раноантичко и римско време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Ограда', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Ограда%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Кале', 'description' => 'раноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Пржали', 'description' => 'железно и римско време', 'link' => 'https://www.openstreetmap.org/search?query=Пржали%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Градиште', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Огради', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Огради%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Калуѓеров Камен', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Калуѓеров Камен%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Дубиче', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Дубиче%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Ливада', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Ливада%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Уши', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Уши%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Црквиште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Црквиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Исар', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Исар%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Св. Димитрија', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Димитрија%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Куќетини', 'description' => 'ран среден век', 'link' => 'https://www.openstreetmap.org/search?query=Куќетини%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Штитиње', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Штитиње%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Градиште', 'description' => 'римско и доцноантичко време; старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Манастириште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Манастириште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Св. Илија', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Св. Илија%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Церје', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Церје%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Бајрамица', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Бајрамица%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Градиште', 'description' => 'железно, раноантичко и римско време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Миљковци', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Миљковци%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Орници', 'description' => 'непознат период', 'link' => 'https://www.openstreetmap.org/search?query=Орници%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Градиште', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Св. Пантелејмон', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Пантелејмон%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Крст', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Крст%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Кале', 'description' => 'римско и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Стара Чешма', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Стара Чешма%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Лозишта', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Лозишта%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Градиште', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Градиште', 'description' => 'римско и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Крушка', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Крушка%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Кале', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Градиште', 'description' => 'римско и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Дервен', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Дервен%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Долно Коњари', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Долно Коњари%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Ограѓе', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Ограѓе%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Вели Поле', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Вели Поле%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Селиште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Селиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Поткарпа', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Поткарпа%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Св. Спас', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Спас%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Чешма', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Чешма%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Белчевица', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Белчевица%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Љубуш', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Љубуш%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Пинтија', 'description' => 'старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Пинтија%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Тресалиште', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Тресалиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Кале', 'description' => 'римско и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Исар', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Исар%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Слатина', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Слатина%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Црквиште', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Црквиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Скупи', 'description' => 'римско и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Скупи%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Илинден', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Илинден%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Падиште', 'description' => 'хеленистичко време', 'link' => 'https://www.openstreetmap.org/search?query=Падиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Доксаница', 'description' => 'неолитско и бронзено време; римско време', 'link' => 'https://www.openstreetmap.org/search?query=Доксаница%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Катланово', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Катланово%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Кочкова Населба', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кочкова Населба%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Рамниште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Рамниште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Црквиште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Црквиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Дренки', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Дренки%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Бошњачка Чешма', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Бошњачка Чешма%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Град', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Град%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Градиште', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Градиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Кучевиште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Кучевиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Радишко', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Радишко%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Бадеми', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Бадеми%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Маркови Кули', 'description' => 'римско и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Маркови Кули%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Љубанци', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Љубанци%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Јазирци', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Јазирци%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Црква', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Црква%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Марково Кале', 'description' => 'римско и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Марково Кале%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Ебишница', 'description' => 'неолитско, бронзено и железно време', 'link' => 'https://www.openstreetmap.org/search?query=Ебишница%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Марков Манастир', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Марков Манастир%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Катуниште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Катуниште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Круша', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Круша%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Куќишта', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Куќишта%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Марков Град', 'description' => 'доцноантичко време и среден век', 'link' => 'https://www.openstreetmap.org/search?query=Марков Град%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Св. Спас', 'description' => 'римско и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Спас%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Ограда', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Ограда%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Тумба', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Ул. „Димче Милошевски“ бр. 139', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Ул. „Димче Милошевски“ бр. 139%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Тумба', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Турски Гробишта', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Турски Гробишта%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Преку Река', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Преку Река%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Шуманица', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Шуманица%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Кавгалија', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кавгалија%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Морани', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Морани%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Сретсело', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Сретсело%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Рамниште', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Рамниште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Селиште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Селиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Барица', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Барица%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Брес', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Брес%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Коњушница', 'description' => 'железно и раноантичко време, доцноантичко време, старохристијанско време', 'link' => 'https://www.openstreetmap.org/search?query=Коњушница%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Манастириште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Манастириште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Св. 40 Маченици', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Св. 40 Маченици%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Ограда', 'description' => 'железно време', 'link' => 'https://www.openstreetmap.org/search?query=Ограда%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Петровец', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Петровец%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Врбиче', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Врбиче%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Гробишта', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Гробишта%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Зајкино', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Зајкино%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Во Селото', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Во Селото%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Голем Град', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Голем Град%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Катастарска Парцела 781', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Катастарска Парцела 781%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Радишко', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Радишко%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Орловица', 'description' => 'неолитско, бронзено и железно време', 'link' => 'https://www.openstreetmap.org/search?query=Орловица%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Чифлик', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Чифлик%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Врело', 'description' => 'бронзено време', 'link' => 'https://www.openstreetmap.org/search?query=Врело%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Долот', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Долот%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Кале', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Пештерка', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Пештерка%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Рашче', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Рашче%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Црква', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Црква%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Шамак', 'description' => 'неолитско време', 'link' => 'https://www.openstreetmap.org/search?query=Шамак%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Рамниште', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Рамниште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Семениште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Семениште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Смиљковце', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Смиљковце%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Кукловец', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Кукловец%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Пржали', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Пржали%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Средно Коњари', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Средно Коњари%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Тумба - Круша', 'description' => 'нелитско и римско време', 'link' => 'https://www.openstreetmap.org/search?query=Тумба - Круша%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Исар - Кале', 'description' => 'раноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Исар - Кале%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Тауресиум (Градиште)', 'description' => 'раноантичко, римско и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Тауресиум (Градиште)%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Св. Илија', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Св. Илија%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Русалија', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Русалија%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Селиште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Селиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Крст', 'description' => 'среден век', 'link' => 'https://www.openstreetmap.org/search?query=Крст%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Црква Св. Атанас', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Црква Св. Атанас%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Крши Дол', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Крши Дол%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Селиште', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Селиште%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Кале', 'description' => 'доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Кале%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Давина Кула', 'description' => 'римско и доцноантичко време', 'link' => 'https://www.openstreetmap.org/search?query=Давина Кула%2C%20Македонија', 'city_id' => 1],
            ['name' => 'Маркова Кула', 'description' => 'римско време', 'link' => 'https://www.openstreetmap.org/search?query=Маркова Кула%2C%20Македонија', 'city_id' => 1],
        ])->each(fn($arPlace) => ArchaeologicalPlace::query()->create($arPlace));
    }
}
